# ~/.bashrc

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

unset LS_OPTIONS
LS_OPTIONS='-F -b -G'
export LS_OPTIONS

HISTCONTROL='ignoredups:erasedups'
IGNOREEOF=1
export HISTCONTROL IGNOREEOF

set -o emacs
set -o histexpand
set -o monitor
set -o notify

shopt -s checkwinsize
shopt -s cmdhist
shopt -s expand_aliases
shopt -s histappend
shopt -s no_empty_cmd_completion
shopt -u huponexit

ulimit -c 0
umask 0077

EDITOR='/usr/bin/vi'
PAGER='less'
export EDITOR PAGER

# turn off special handling of ._* files in tar, etc.
# see http://superuser.com/questions/259703/get-mac-tar-to-stop-putting-filenames-in-tar-archives
COPYFILE_DISABLE=1
export COPYFILE_DISABLE

source ~/.bash_alias
source ~/.bash_local

set -o history
